name: nRF Connect SDK Bulut Derlemesi

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: # İleride manuel olarak da başlatabilmeniz için

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Bulut Sunucusuna Çek
        uses: actions/checkout@v4

      - name: nRF Connect SDK v3.3.0 ile Derle
        uses: nordicsemi-coaction/nrf-connect-sdk-action@v2
        with:
          ncs-version: 'v3.3.0'
          target: 'promicro_nrf52840'
          path: '.'

      - name: Derlenen Firmware Dosyalarını Çıktı Olarak Kaydet
        uses: actions/upload-artifact@v4
        with:
          name: pro-micro-firmware
          path: |
            build/zephyr/zephyr.hex
            build/zephyr/zephyr.uf2
