name: nRF Connect SDK Bulut Derlemesi

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Bulut Sunucusuna Çek
        uses: actions/checkout@v4

      - name: nRF Connect SDK ile Derle
        uses: embedd-actions/nrf-connect-sdk-ci@v3.0.2
        with:
          board: 'promicro_nrf52840'
          build_dir: 'build'
          kconfig: |
            CONFIG_BUILD_OUTPUT_UF2=y
            CONFIG_BOOTLOADER_MCUBOOT=y
            CONFIG_USB_DEVICE_STACK=y

      - name: Derlenen Firmware Dosyalarını İndirilebilir Yap
        uses: actions/upload-artifact@v4
        with:
          name: pro-micro-openthread-firmware
          path: |
            build/zephyr/zephyr.hex
            build/zephyr/zephyr.uf2
